version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    working_directory: /build/
    steps:
      - checkout
      - run:
          name: Build Project
          command: |
            pushd ./PitStopBot/
            dotnet publish -c Release -o /build/out
            popd
